name: sun_flutter_capstone
description: Sun Asterisk Flutter Capstone

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  auto_route: ^3.2.4
  hooks_riverpod: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  auto_route_generator: ^3.2.3
  build_runner: ^2.1.10
  git_hooks: ^0.1.6

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
